/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package progettogdr;

/**
 *
 * @author pasqui.filippo
 */
public class HomeForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeForm.class.getName());
       private FormGioco fm; 
       private String nome; 
        
    public HomeForm() {
        initComponents();
        fm=new FormGioco();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAxel = new javax.swing.JLabel();
        lblAitor = new javax.swing.JLabel();
        lblShawn = new javax.swing.JLabel();
        btnInfoShawn = new javax.swing.JButton();
        btnInfoAitor = new javax.swing.JButton();
        btnInfoAxel = new javax.swing.JButton();
        btnSelectAxel = new javax.swing.JButton();
        btnSelectAitor = new javax.swing.JButton();
        btnSelectShawn = new javax.swing.JButton();
        lblSfondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAxel.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        lblAxel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAxel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettogdr/foto/axel.png"))); // NOI18N
        getContentPane().add(lblAxel, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 150, 460));

        lblAitor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAitor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettogdr/foto/aitor.png"))); // NOI18N
        lblAitor.setText("jLabel2");
        getContentPane().add(lblAitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 190, 450));

        lblShawn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblShawn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettogdr/foto/shawn.png"))); // NOI18N
        lblShawn.setText("jLabel2");
        getContentPane().add(lblShawn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 170, 390));

        btnInfoShawn.setBackground(new java.awt.Color(51, 51, 255));
        btnInfoShawn.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnInfoShawn.setForeground(new java.awt.Color(255, 255, 255));
        btnInfoShawn.setText("i");
        btnInfoShawn.setFocusPainted(false);
        btnInfoShawn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoShawnActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfoShawn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 40, 40));

        btnInfoAitor.setBackground(new java.awt.Color(51, 51, 255));
        btnInfoAitor.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnInfoAitor.setForeground(new java.awt.Color(255, 255, 255));
        btnInfoAitor.setText("i");
        btnInfoAitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoAitorActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfoAitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 130, 40, 40));

        btnInfoAxel.setBackground(new java.awt.Color(51, 51, 255));
        btnInfoAxel.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        btnInfoAxel.setForeground(new java.awt.Color(255, 255, 255));
        btnInfoAxel.setText("i");
        btnInfoAxel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoAxelActionPerformed(evt);
            }
        });
        getContentPane().add(btnInfoAxel, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 110, 40, 40));

        btnSelectAxel.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        btnSelectAxel.setText("AXEL blaze");
        btnSelectAxel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectAxelActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectAxel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, 130, 40));

        btnSelectAitor.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        btnSelectAitor.setText("aitor cazador");
        btnSelectAitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectAitorActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectAitor, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 530, 150, 40));

        btnSelectShawn.setFont(new java.awt.Font("Stencil", 0, 14)); // NOI18N
        btnSelectShawn.setText("Shawn Frost");
        btnSelectShawn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectShawnActionPerformed(evt);
            }
        });
        getContentPane().add(btnSelectShawn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 530, 140, 40));

        lblSfondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettogdr/foto/sfondoHome.png"))); // NOI18N
        lblSfondo.setText("jLabel1");
        getContentPane().add(lblSfondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-130, 0, 1250, 620));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSelectAitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectAitorActionPerformed
        nome="aitor";
        fm.setImage(nome);
        fm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSelectAitorActionPerformed

    private void btnInfoAxelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoAxelActionPerformed
       AxelForm a1=new AxelForm();
        a1.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnInfoAxelActionPerformed

    private void btnInfoAitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoAitorActionPerformed
       AitorForm c1=new AitorForm();
        c1.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnInfoAitorActionPerformed

    private void btnInfoShawnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoShawnActionPerformed
       ShawnForm s1=new ShawnForm();
        s1.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnInfoShawnActionPerformed

    private void btnSelectShawnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectShawnActionPerformed
        nome="shawn";
        fm.setImage(nome);
        fm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSelectShawnActionPerformed

    private void btnSelectAxelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectAxelActionPerformed
        nome="axel";
        fm.setImage(nome);
        fm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSelectAxelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HomeForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInfoAitor;
    private javax.swing.JButton btnInfoAxel;
    private javax.swing.JButton btnInfoShawn;
    private javax.swing.JButton btnSelectAitor;
    private javax.swing.JButton btnSelectAxel;
    private javax.swing.JButton btnSelectShawn;
    private javax.swing.JLabel lblAitor;
    private javax.swing.JLabel lblAxel;
    private javax.swing.JLabel lblSfondo;
    private javax.swing.JLabel lblShawn;
    // End of variables declaration//GEN-END:variables
}
